# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WECLauncher.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1125, 929)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Friz Quadrata Std")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(6, 26, 37);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_1 = QtWidgets.QPushButton(self.centralwidget)
        self.button_1.setGeometry(QtCore.QRect(500, 40, 111, 31))
        self.button_1.setAcceptDrops(False)
        self.button_1.setStyleSheet("background-color: rgb(157, 130, 84);\n"
"font: 75 16pt \"Ebrima\";")
        self.button_1.setObjectName("button_1")
        self.labelRoot = QtWidgets.QLabel(self.centralwidget)
        self.labelRoot.setGeometry(QtCore.QRect(10, 860, 141, 16))
        self.labelRoot.setStyleSheet("color: rgb(157, 130, 84);")
        self.labelRoot.setObjectName("labelRoot")
        self.labelMain = QtWidgets.QLabel(self.centralwidget)
        self.labelMain.setGeometry(QtCore.QRect(10, 0, 191, 21))
        self.labelMain.setStyleSheet("color: rgb(157, 130, 84);\n"
"font: 63 11pt \"Yu Gothic UI Semibold\";")
        self.labelMain.setObjectName("labelMain")
        self.labelSUP = QtWidgets.QLabel(self.centralwidget)
        self.labelSUP.setGeometry(QtCore.QRect(520, 720, 71, 71))
        self.labelSUP.setText("")
        self.labelSUP.setPixmap(QtGui.QPixmap("ressources/0_SUP.png"))
        self.labelSUP.setScaledContents(True)
        self.labelSUP.setObjectName("labelSUP")
        self.labelBot = QtWidgets.QLabel(self.centralwidget)
        self.labelBot.setGeometry(QtCore.QRect(520, 600, 71, 71))
        self.labelBot.setText("")
        self.labelBot.setPixmap(QtGui.QPixmap("ressources/0_BOT.png"))
        self.labelBot.setScaledContents(True)
        self.labelBot.setObjectName("labelBot")
        self.labelMid = QtWidgets.QLabel(self.centralwidget)
        self.labelMid.setGeometry(QtCore.QRect(520, 480, 71, 71))
        self.labelMid.setText("")
        self.labelMid.setPixmap(QtGui.QPixmap("ressources/0_MID.png"))
        self.labelMid.setScaledContents(True)
        self.labelMid.setObjectName("labelMid")
        self.labelJGL = QtWidgets.QLabel(self.centralwidget)
        self.labelJGL.setGeometry(QtCore.QRect(520, 360, 71, 71))
        self.labelJGL.setText("")
        self.labelJGL.setPixmap(QtGui.QPixmap("ressources/0_JGL.png"))
        self.labelJGL.setScaledContents(True)
        self.labelJGL.setObjectName("labelJGL")
        self.labelTOP = QtWidgets.QLabel(self.centralwidget)
        self.labelTOP.setGeometry(QtCore.QRect(520, 240, 71, 71))
        self.labelTOP.setText("")
        self.labelTOP.setPixmap(QtGui.QPixmap("ressources/0_TOP.png"))
        self.labelTOP.setScaledContents(True)
        self.labelTOP.setObjectName("labelTOP")
        self.textBlueTop = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBlueTop.setGeometry(QtCore.QRect(160, 250, 331, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.textBlueTop.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Friz Quadrata")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.textBlueTop.setFont(font)
        self.textBlueTop.setStyleSheet("background-color: rgb(20, 244, 255);")
        self.textBlueTop.setObjectName("textBlueTop")
        self.textBlueJgl = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBlueJgl.setGeometry(QtCore.QRect(160, 370, 331, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.textBlueJgl.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Friz Quadrata")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.textBlueJgl.setFont(font)
        self.textBlueJgl.setStyleSheet("background-color: rgb(20, 244, 255);")
        self.textBlueJgl.setObjectName("textBlueJgl")
        self.textBlueMid = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBlueMid.setGeometry(QtCore.QRect(160, 490, 331, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.textBlueMid.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Friz Quadrata")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.textBlueMid.setFont(font)
        self.textBlueMid.setStyleSheet("background-color: rgb(20, 244, 255);")
        self.textBlueMid.setObjectName("textBlueMid")
        self.textBlueBot = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBlueBot.setGeometry(QtCore.QRect(160, 610, 331, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.textBlueBot.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Friz Quadrata")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.textBlueBot.setFont(font)
        self.textBlueBot.setStyleSheet("background-color: rgb(20, 244, 255);")
        self.textBlueBot.setObjectName("textBlueBot")
        self.textBlueSup = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBlueSup.setGeometry(QtCore.QRect(160, 730, 331, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 244, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.textBlueSup.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Friz Quadrata")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.textBlueSup.setFont(font)
        self.textBlueSup.setStyleSheet("background-color: rgb(20, 244, 255);")
        self.textBlueSup.setObjectName("textBlueSup")
        self.textRedTop = QtWidgets.QTextBrowser(self.centralwidget)
        self.textRedTop.setGeometry(QtCore.QRect(620, 250, 331, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.textRedTop.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Friz Quadrata")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.textRedTop.setFont(font)
        self.textRedTop.setStyleSheet("background-color: rgb(255, 139, 141);")
        self.textRedTop.setObjectName("textRedTop")
        self.textRedJgl = QtWidgets.QTextBrowser(self.centralwidget)
        self.textRedJgl.setGeometry(QtCore.QRect(620, 370, 331, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.textRedJgl.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Friz Quadrata")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.textRedJgl.setFont(font)
        self.textRedJgl.setStyleSheet("background-color: rgb(255, 139, 141);")
        self.textRedJgl.setObjectName("textRedJgl")
        self.textRedMid = QtWidgets.QTextBrowser(self.centralwidget)
        self.textRedMid.setGeometry(QtCore.QRect(620, 490, 331, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.textRedMid.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Friz Quadrata")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.textRedMid.setFont(font)
        self.textRedMid.setStyleSheet("background-color: rgb(255, 139, 141);")
        self.textRedMid.setObjectName("textRedMid")
        self.textRedBot = QtWidgets.QTextBrowser(self.centralwidget)
        self.textRedBot.setGeometry(QtCore.QRect(620, 610, 331, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.textRedBot.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Friz Quadrata")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.textRedBot.setFont(font)
        self.textRedBot.setStyleSheet("background-color: rgb(255, 139, 141);")
        self.textRedBot.setObjectName("textRedBot")
        self.textRedSup = QtWidgets.QTextBrowser(self.centralwidget)
        self.textRedSup.setGeometry(QtCore.QRect(620, 730, 331, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 139, 141))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.textRedSup.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Friz Quadrata")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.textRedSup.setFont(font)
        self.textRedSup.setStyleSheet("background-color: rgb(255, 139, 141);")
        self.textRedSup.setObjectName("textRedSup")
        self.infoButton = QtWidgets.QPushButton(self.centralwidget)
        self.infoButton.setGeometry(QtCore.QRect(150, 850, 21, 23))
        self.infoButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ressources/icon/information-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.infoButton.setIcon(icon)
        self.infoButton.setIconSize(QtCore.QSize(24, 24))
        self.infoButton.setObjectName("infoButton")
        self.textBlueMain = QtWidgets.QLineEdit(self.centralwidget)
        self.textBlueMain.setGeometry(QtCore.QRect(160, 140, 331, 61))
        font = QtGui.QFont()
        font.setFamily("Friz Quadrata")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textBlueMain.setFont(font)
        self.textBlueMain.setStyleSheet("background-color: rgb(10, 128, 255);")
        self.textBlueMain.setAlignment(QtCore.Qt.AlignCenter)
        self.textBlueMain.setObjectName("textBlueMain")
        self.textRedMain = QtWidgets.QLineEdit(self.centralwidget)
        self.textRedMain.setGeometry(QtCore.QRect(620, 140, 331, 61))
        font = QtGui.QFont()
        font.setFamily("Friz Quadrata")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textRedMain.setFont(font)
        self.textRedMain.setStyleSheet("background-color: rgb(255, 90, 93);")
        self.textRedMain.setAlignment(QtCore.Qt.AlignCenter)
        self.textRedMain.setObjectName("textRedMain")
        self.imgBlueTop = QtWidgets.QLabel(self.centralwidget)
        self.imgBlueTop.setGeometry(QtCore.QRect(30, 230, 91, 91))
        self.imgBlueTop.setStyleSheet("border-color: rgb(255, 255, 127);")
        self.imgBlueTop.setFrameShape(QtWidgets.QFrame.Box)
        self.imgBlueTop.setLineWidth(0)
        self.imgBlueTop.setText("")
        self.imgBlueTop.setAlignment(QtCore.Qt.AlignCenter)
        self.imgBlueTop.setObjectName("imgBlueTop")
        self.imgBlueJgl = QtWidgets.QLabel(self.centralwidget)
        self.imgBlueJgl.setGeometry(QtCore.QRect(30, 350, 91, 91))
        self.imgBlueJgl.setStyleSheet("border-color: rgb(255, 255, 127);")
        self.imgBlueJgl.setFrameShape(QtWidgets.QFrame.Box)
        self.imgBlueJgl.setLineWidth(0)
        self.imgBlueJgl.setText("")
        self.imgBlueJgl.setAlignment(QtCore.Qt.AlignCenter)
        self.imgBlueJgl.setObjectName("imgBlueJgl")
        self.imgBlueMid = QtWidgets.QLabel(self.centralwidget)
        self.imgBlueMid.setGeometry(QtCore.QRect(30, 470, 91, 91))
        self.imgBlueMid.setStyleSheet("border-color: rgb(255, 255, 127);")
        self.imgBlueMid.setFrameShape(QtWidgets.QFrame.Box)
        self.imgBlueMid.setLineWidth(0)
        self.imgBlueMid.setText("")
        self.imgBlueMid.setAlignment(QtCore.Qt.AlignCenter)
        self.imgBlueMid.setObjectName("imgBlueMid")
        self.imgBlueBot = QtWidgets.QLabel(self.centralwidget)
        self.imgBlueBot.setGeometry(QtCore.QRect(30, 590, 91, 91))
        self.imgBlueBot.setStyleSheet("border-color: rgb(255, 255, 127);")
        self.imgBlueBot.setFrameShape(QtWidgets.QFrame.Box)
        self.imgBlueBot.setLineWidth(0)
        self.imgBlueBot.setText("")
        self.imgBlueBot.setAlignment(QtCore.Qt.AlignCenter)
        self.imgBlueBot.setObjectName("imgBlueBot")
        self.imgBlueSup = QtWidgets.QLabel(self.centralwidget)
        self.imgBlueSup.setGeometry(QtCore.QRect(30, 710, 91, 91))
        self.imgBlueSup.setStyleSheet("border-color: rgb(255, 255, 127);")
        self.imgBlueSup.setFrameShape(QtWidgets.QFrame.Box)
        self.imgBlueSup.setLineWidth(0)
        self.imgBlueSup.setText("")
        self.imgBlueSup.setAlignment(QtCore.Qt.AlignCenter)
        self.imgBlueSup.setObjectName("imgBlueSup")
        self.imgRedTop = QtWidgets.QLabel(self.centralwidget)
        self.imgRedTop.setGeometry(QtCore.QRect(980, 230, 91, 91))
        self.imgRedTop.setStyleSheet("border-color: rgb(255, 255, 127);")
        self.imgRedTop.setFrameShape(QtWidgets.QFrame.Box)
        self.imgRedTop.setLineWidth(0)
        self.imgRedTop.setText("")
        self.imgRedTop.setAlignment(QtCore.Qt.AlignCenter)
        self.imgRedTop.setObjectName("imgRedTop")
        self.imgRedJgl = QtWidgets.QLabel(self.centralwidget)
        self.imgRedJgl.setGeometry(QtCore.QRect(980, 350, 91, 91))
        self.imgRedJgl.setStyleSheet("border-color: rgb(255, 255, 127);")
        self.imgRedJgl.setFrameShape(QtWidgets.QFrame.Box)
        self.imgRedJgl.setLineWidth(0)
        self.imgRedJgl.setText("")
        self.imgRedJgl.setAlignment(QtCore.Qt.AlignCenter)
        self.imgRedJgl.setObjectName("imgRedJgl")
        self.imgRedMid = QtWidgets.QLabel(self.centralwidget)
        self.imgRedMid.setGeometry(QtCore.QRect(980, 470, 91, 91))
        self.imgRedMid.setStyleSheet("border-color: rgb(255, 255, 127);")
        self.imgRedMid.setFrameShape(QtWidgets.QFrame.Box)
        self.imgRedMid.setLineWidth(0)
        self.imgRedMid.setText("")
        self.imgRedMid.setAlignment(QtCore.Qt.AlignCenter)
        self.imgRedMid.setObjectName("imgRedMid")
        self.imgRedBot = QtWidgets.QLabel(self.centralwidget)
        self.imgRedBot.setGeometry(QtCore.QRect(980, 590, 91, 91))
        self.imgRedBot.setStyleSheet("border-color: rgb(255, 255, 127);")
        self.imgRedBot.setFrameShape(QtWidgets.QFrame.Box)
        self.imgRedBot.setLineWidth(0)
        self.imgRedBot.setText("")
        self.imgRedBot.setAlignment(QtCore.Qt.AlignCenter)
        self.imgRedBot.setObjectName("imgRedBot")
        self.imgRedSup = QtWidgets.QLabel(self.centralwidget)
        self.imgRedSup.setGeometry(QtCore.QRect(980, 710, 91, 91))
        self.imgRedSup.setStyleSheet("border-color: rgb(255, 255, 127);")
        self.imgRedSup.setFrameShape(QtWidgets.QFrame.Box)
        self.imgRedSup.setLineWidth(0)
        self.imgRedSup.setText("")
        self.imgRedSup.setAlignment(QtCore.Qt.AlignCenter)
        self.imgRedSup.setObjectName("imgRedSup")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(520, 140, 71, 71))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("ressources/Versus_2.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1125, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionpgmLauncher = QtWidgets.QAction(MainWindow)
        self.actionpgmLauncher.setObjectName("actionpgmLauncher")

        self.retranslateUi(MainWindow)
        self.button_1.clicked.connect(self.actionpgmLauncher.trigger)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WEC - Data Alchemist Studio, 2021"))
        self.button_1.setText(_translate("MainWindow", "LANCER"))
        self.labelRoot.setText(_translate("MainWindow", "Data Alchemist Studio, 2021"))
        self.labelMain.setText(_translate("MainWindow", "Win Expectancy Calculation"))
        self.actionpgmLauncher.setText(_translate("MainWindow", "pgmLauncher"))

