# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WECPrevLauncher.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import Fonctions_Live as fl

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1125, 929)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Friz Quadrata Std")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(6, 26, 37);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_1 = QtWidgets.QPushButton(self.centralwidget)
        self.button_1.setGeometry(QtCore.QRect(500, 40, 111, 31))
        self.button_1.setAcceptDrops(False)
        self.button_1.setStyleSheet("background-color: rgb(157, 130, 84);\n"
"font: 75 16pt \"Ebrima\";")
        self.button_1.setObjectName("button_1")
        self.labelSUP = QtWidgets.QLabel(self.centralwidget)
        self.labelSUP.setGeometry(QtCore.QRect(520, 720, 71, 71))
        self.labelSUP.setText("")
        self.labelSUP.setPixmap(QtGui.QPixmap("ressources/0_SUP.png"))
        self.labelSUP.setScaledContents(True)
        self.labelSUP.setObjectName("labelSUP")
        self.labelBot = QtWidgets.QLabel(self.centralwidget)
        self.labelBot.setGeometry(QtCore.QRect(520, 600, 71, 71))
        self.labelBot.setText("")
        self.labelBot.setPixmap(QtGui.QPixmap("ressources/0_BOT.png"))
        self.labelBot.setScaledContents(True)
        self.labelBot.setObjectName("labelBot")
        self.labelMid = QtWidgets.QLabel(self.centralwidget)
        self.labelMid.setGeometry(QtCore.QRect(520, 480, 71, 71))
        self.labelMid.setText("")
        self.labelMid.setPixmap(QtGui.QPixmap("ressources/0_MID.png"))
        self.labelMid.setScaledContents(True)
        self.labelMid.setObjectName("labelMid")
        self.labelJGL = QtWidgets.QLabel(self.centralwidget)
        self.labelJGL.setGeometry(QtCore.QRect(520, 360, 71, 71))
        self.labelJGL.setText("")
        self.labelJGL.setPixmap(QtGui.QPixmap("ressources/0_JGL.png"))
        self.labelJGL.setScaledContents(True)
        self.labelJGL.setObjectName("labelJGL")
        self.labelTOP = QtWidgets.QLabel(self.centralwidget)
        self.labelTOP.setGeometry(QtCore.QRect(520, 240, 71, 71))
        self.labelTOP.setText("")
        self.labelTOP.setPixmap(QtGui.QPixmap("ressources/0_TOP.png"))
        self.labelTOP.setScaledContents(True)
        self.labelTOP.setObjectName("labelTOP")
        self.textBlueTop = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBlueTop.setGeometry(QtCore.QRect(160, 240, 331, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.textBlueTop.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Display ExtraCondensed")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textBlueTop.setFont(font)
        self.textBlueTop.setStyleSheet("background-color: rgb(6, 26, 37);\n"
"border-color: rgb(6, 26, 37);\n"
"color: rgb(223, 190, 122);")
        self.textBlueTop.setLineWidth(0)
        self.textBlueTop.setObjectName("textBlueTop")
        self.textBlueJgl = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBlueJgl.setGeometry(QtCore.QRect(160, 360, 331, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.textBlueJgl.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Display ExtraCondensed")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textBlueJgl.setFont(font)
        self.textBlueJgl.setStyleSheet("background-color: rgb(6, 26, 37);\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(223, 190, 122);\n"
"border : 2px;")
        self.textBlueJgl.setLineWidth(0)
        self.textBlueJgl.setObjectName("textBlueJgl")
        self.textBlueMid = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBlueMid.setGeometry(QtCore.QRect(160, 480, 331, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.textBlueMid.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Display ExtraCondensed")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textBlueMid.setFont(font)
        self.textBlueMid.setStyleSheet("background-color: rgb(6, 26, 37);\n"
"color: rgb(223, 190, 122);\n"
"border-color: rgb(6, 26, 37);")
        self.textBlueMid.setLineWidth(0)
        self.textBlueMid.setObjectName("textBlueMid")
        self.textBlueBot = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBlueBot.setGeometry(QtCore.QRect(160, 600, 331, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.textBlueBot.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Display ExtraCondensed")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textBlueBot.setFont(font)
        self.textBlueBot.setStyleSheet("background-color: rgb(6, 26, 37);\n"
"color: rgb(223, 190, 122);\n"
"border-color: rgb(6, 26, 37);")
        self.textBlueBot.setLineWidth(0)
        self.textBlueBot.setObjectName("textBlueBot")
        self.textBlueSup = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBlueSup.setGeometry(QtCore.QRect(160, 720, 331, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.textBlueSup.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Display ExtraCondensed")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textBlueSup.setFont(font)
        self.textBlueSup.setStyleSheet("background-color: rgb(6, 26, 37);\n"
"color: rgb(223, 190, 122);\n"
"border-color: rgb(6, 26, 37);")
        self.textBlueSup.setLineWidth(0)
        self.textBlueSup.setObjectName("textBlueSup")
        self.textRedTop = QtWidgets.QTextBrowser(self.centralwidget)
        self.textRedTop.setGeometry(QtCore.QRect(620, 240, 331, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.textRedTop.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Display ExtraCondensed")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textRedTop.setFont(font)
        self.textRedTop.setStyleSheet("background-color: rgb(6, 26, 37);\n"
"color: rgb(223, 190, 122);\n"
"border-color: rgb(6, 26, 37);")
        self.textRedTop.setObjectName("textRedTop")
        self.textRedJgl = QtWidgets.QTextBrowser(self.centralwidget)
        self.textRedJgl.setGeometry(QtCore.QRect(620, 360, 331, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.textRedJgl.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Display ExtraCondensed")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textRedJgl.setFont(font)
        self.textRedJgl.setStyleSheet("background-color: rgb(6, 26, 37);\n"
"color: rgb(223, 190, 122);\n"
"border-color: rgb(6, 26, 37);")
        self.textRedJgl.setObjectName("textRedJgl")
        self.textRedMid = QtWidgets.QTextBrowser(self.centralwidget)
        self.textRedMid.setGeometry(QtCore.QRect(620, 480, 331, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.textRedMid.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Display ExtraCondensed")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textRedMid.setFont(font)
        self.textRedMid.setStyleSheet("background-color: rgb(6, 26, 37);\n"
"color: rgb(223, 190, 122);\n"
"border-color: rgb(6, 26, 37);")
        self.textRedMid.setObjectName("textRedMid")
        self.textRedBot = QtWidgets.QTextBrowser(self.centralwidget)
        self.textRedBot.setGeometry(QtCore.QRect(620, 600, 331, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.textRedBot.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Display ExtraCondensed")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textRedBot.setFont(font)
        self.textRedBot.setStyleSheet("background-color: rgb(6, 26, 37);\n"
"color: rgb(223, 190, 122);\n"
"border-color: rgb(6, 26, 37);")
        self.textRedBot.setObjectName("textRedBot")
        self.textRedSup = QtWidgets.QTextBrowser(self.centralwidget)
        self.textRedSup.setGeometry(QtCore.QRect(620, 720, 331, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(223, 190, 122))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 26, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.textRedSup.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Display ExtraCondensed")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textRedSup.setFont(font)
        self.textRedSup.setStyleSheet("background-color: rgb(6, 26, 37);\n"
"color: rgb(223, 190, 122);\n"
"border-color: rgb(6, 26, 37);")
        self.textRedSup.setObjectName("textRedSup")
        self.imgBlueTop = QtWidgets.QLabel(self.centralwidget)
        self.imgBlueTop.setGeometry(QtCore.QRect(30, 230, 91, 91))
        self.imgBlueTop.setStyleSheet("border-color: rgb(255, 255, 127);")
        self.imgBlueTop.setFrameShape(QtWidgets.QFrame.Box)
        self.imgBlueTop.setLineWidth(0)
        self.imgBlueTop.setText("")
        self.imgBlueTop.setAlignment(QtCore.Qt.AlignCenter)
        self.imgBlueTop.setObjectName("imgBlueTop")
        self.imgBlueJgl = QtWidgets.QLabel(self.centralwidget)
        self.imgBlueJgl.setGeometry(QtCore.QRect(30, 350, 91, 91))
        self.imgBlueJgl.setStyleSheet("border-color: rgb(255, 255, 127);")
        self.imgBlueJgl.setFrameShape(QtWidgets.QFrame.Box)
        self.imgBlueJgl.setLineWidth(0)
        self.imgBlueJgl.setText("")
        self.imgBlueJgl.setAlignment(QtCore.Qt.AlignCenter)
        self.imgBlueJgl.setObjectName("imgBlueJgl")
        self.imgBlueMid = QtWidgets.QLabel(self.centralwidget)
        self.imgBlueMid.setGeometry(QtCore.QRect(30, 470, 91, 91))
        self.imgBlueMid.setStyleSheet("border-color: rgb(255, 255, 127);")
        self.imgBlueMid.setFrameShape(QtWidgets.QFrame.Box)
        self.imgBlueMid.setLineWidth(0)
        self.imgBlueMid.setText("")
        self.imgBlueMid.setAlignment(QtCore.Qt.AlignCenter)
        self.imgBlueMid.setObjectName("imgBlueMid")
        self.imgBlueBot = QtWidgets.QLabel(self.centralwidget)
        self.imgBlueBot.setGeometry(QtCore.QRect(30, 590, 91, 91))
        self.imgBlueBot.setStyleSheet("border-color: rgb(255, 255, 127);")
        self.imgBlueBot.setFrameShape(QtWidgets.QFrame.Box)
        self.imgBlueBot.setLineWidth(0)
        self.imgBlueBot.setText("")
        self.imgBlueBot.setAlignment(QtCore.Qt.AlignCenter)
        self.imgBlueBot.setObjectName("imgBlueBot")
        self.imgBlueSup = QtWidgets.QLabel(self.centralwidget)
        self.imgBlueSup.setGeometry(QtCore.QRect(30, 710, 91, 91))
        self.imgBlueSup.setStyleSheet("border-color: rgb(255, 255, 127);")
        self.imgBlueSup.setFrameShape(QtWidgets.QFrame.Box)
        self.imgBlueSup.setLineWidth(0)
        self.imgBlueSup.setText("")
        self.imgBlueSup.setAlignment(QtCore.Qt.AlignCenter)
        self.imgBlueSup.setObjectName("imgBlueSup")
        self.imgRedTop = QtWidgets.QLabel(self.centralwidget)
        self.imgRedTop.setGeometry(QtCore.QRect(980, 230, 91, 91))
        self.imgRedTop.setStyleSheet("border-color: rgb(255, 255, 127);")
        self.imgRedTop.setFrameShape(QtWidgets.QFrame.Box)
        self.imgRedTop.setLineWidth(0)
        self.imgRedTop.setText("")
        self.imgRedTop.setAlignment(QtCore.Qt.AlignCenter)
        self.imgRedTop.setObjectName("imgRedTop")
        self.imgRedJgl = QtWidgets.QLabel(self.centralwidget)
        self.imgRedJgl.setGeometry(QtCore.QRect(980, 350, 91, 91))
        self.imgRedJgl.setStyleSheet("border-color: rgb(255, 255, 127);")
        self.imgRedJgl.setFrameShape(QtWidgets.QFrame.Box)
        self.imgRedJgl.setLineWidth(0)
        self.imgRedJgl.setText("")
        self.imgRedJgl.setAlignment(QtCore.Qt.AlignCenter)
        self.imgRedJgl.setObjectName("imgRedJgl")
        self.imgRedMid = QtWidgets.QLabel(self.centralwidget)
        self.imgRedMid.setGeometry(QtCore.QRect(980, 470, 91, 91))
        self.imgRedMid.setStyleSheet("border-color: rgb(255, 255, 127);")
        self.imgRedMid.setFrameShape(QtWidgets.QFrame.Box)
        self.imgRedMid.setLineWidth(0)
        self.imgRedMid.setText("")
        self.imgRedMid.setAlignment(QtCore.Qt.AlignCenter)
        self.imgRedMid.setObjectName("imgRedMid")
        self.imgRedBot = QtWidgets.QLabel(self.centralwidget)
        self.imgRedBot.setGeometry(QtCore.QRect(980, 590, 91, 91))
        self.imgRedBot.setStyleSheet("border-color: rgb(255, 255, 127);")
        self.imgRedBot.setFrameShape(QtWidgets.QFrame.Box)
        self.imgRedBot.setLineWidth(0)
        self.imgRedBot.setText("")
        self.imgRedBot.setAlignment(QtCore.Qt.AlignCenter)
        self.imgRedBot.setObjectName("imgRedBot")
        self.imgRedSup = QtWidgets.QLabel(self.centralwidget)
        self.imgRedSup.setGeometry(QtCore.QRect(980, 710, 91, 91))
        self.imgRedSup.setStyleSheet("border-color: rgb(255, 255, 127);")
        self.imgRedSup.setFrameShape(QtWidgets.QFrame.Box)
        self.imgRedSup.setLineWidth(0)
        self.imgRedSup.setText("")
        self.imgRedSup.setAlignment(QtCore.Qt.AlignCenter)
        self.imgRedSup.setObjectName("imgRedSup")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(520, 140, 71, 71))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("ressources/Versus_2.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.textRedMain = QtWidgets.QTextBrowser(self.centralwidget)
        self.textRedMain.setGeometry(QtCore.QRect(620, 140, 331, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(113, 96, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(241, 85, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 96, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 96, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(241, 85, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(241, 85, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 96, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(241, 85, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 96, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 96, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(241, 85, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(241, 85, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 96, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(241, 85, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 96, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 96, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(241, 85, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(241, 85, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.textRedMain.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Display Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.textRedMain.setFont(font)
        self.textRedMain.setStyleSheet("background-color: rgb(241, 85, 88);\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(6, 26, 37);")
        self.textRedMain.setObjectName("textRedMain")
        self.textBlueMain = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBlueMain.setGeometry(QtCore.QRect(160, 140, 331, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(113, 96, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 128, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 96, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 96, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 128, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 128, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 96, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 128, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 96, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 96, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 128, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 128, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 96, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 128, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 96, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 96, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 128, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 128, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.textBlueMain.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Display Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.textBlueMain.setFont(font)
        self.textBlueMain.setStyleSheet("background-color: rgb(10, 128, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(6, 26, 37);")
        self.textBlueMain.setObjectName("textBlueMain")
        self.SNBlueTop = QtWidgets.QLineEdit(self.centralwidget)
        self.SNBlueTop.setGeometry(QtCore.QRect(154, 230, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SNBlueTop.setFont(font)
        self.SNBlueTop.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SNBlueTop.setMaxLength(16)
        self.SNBlueTop.setObjectName("SNBlueTop")
        self.SNRedTop = QtWidgets.QLineEdit(self.centralwidget)
        self.SNRedTop.setGeometry(QtCore.QRect(810, 230, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SNRedTop.setFont(font)
        self.SNRedTop.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SNRedTop.setMaxLength(16)
        self.SNRedTop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.SNRedTop.setObjectName("SNRedTop")
        self.SNRedJungle = QtWidgets.QLineEdit(self.centralwidget)
        self.SNRedJungle.setGeometry(QtCore.QRect(810, 350, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SNRedJungle.setFont(font)
        self.SNRedJungle.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SNRedJungle.setMaxLength(16)
        self.SNRedJungle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.SNRedJungle.setObjectName("SNRedJungle")
        self.SNBlueJungle = QtWidgets.QLineEdit(self.centralwidget)
        self.SNBlueJungle.setGeometry(QtCore.QRect(150, 350, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SNBlueJungle.setFont(font)
        self.SNBlueJungle.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SNBlueJungle.setMaxLength(16)
        self.SNBlueJungle.setObjectName("SNBlueJungle")
        self.SNBlueMid = QtWidgets.QLineEdit(self.centralwidget)
        self.SNBlueMid.setGeometry(QtCore.QRect(150, 470, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SNBlueMid.setFont(font)
        self.SNBlueMid.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SNBlueMid.setMaxLength(16)
        self.SNBlueMid.setObjectName("SNBlueMid")
        self.SNRedMid = QtWidgets.QLineEdit(self.centralwidget)
        self.SNRedMid.setGeometry(QtCore.QRect(810, 470, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SNRedMid.setFont(font)
        self.SNRedMid.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SNRedMid.setMaxLength(16)
        self.SNRedMid.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.SNRedMid.setObjectName("SNRedMid")
        self.SNBlueBot = QtWidgets.QLineEdit(self.centralwidget)
        self.SNBlueBot.setGeometry(QtCore.QRect(150, 590, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SNBlueBot.setFont(font)
        self.SNBlueBot.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SNBlueBot.setMaxLength(16)
        self.SNBlueBot.setObjectName("SNBlueBot")
        self.SNRedBot = QtWidgets.QLineEdit(self.centralwidget)
        self.SNRedBot.setGeometry(QtCore.QRect(810, 594, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SNRedBot.setFont(font)
        self.SNRedBot.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SNRedBot.setMaxLength(16)
        self.SNRedBot.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.SNRedBot.setObjectName("SNRedBot")
        self.SNRedSup = QtWidgets.QLineEdit(self.centralwidget)
        self.SNRedSup.setGeometry(QtCore.QRect(810, 710, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SNRedSup.setFont(font)
        self.SNRedSup.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SNRedSup.setMaxLength(16)
        self.SNRedSup.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.SNRedSup.setObjectName("SNRedSup")
        self.SNBlueSup = QtWidgets.QLineEdit(self.centralwidget)
        self.SNBlueSup.setGeometry(QtCore.QRect(151, 714, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SNBlueSup.setFont(font)
        self.SNBlueSup.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SNBlueSup.setMaxLength(16)
        self.SNBlueSup.setObjectName("SNBlueSup")
        self.ChampBlueTop = QtWidgets.QComboBox(self.centralwidget)
        self.ChampBlueTop.setGeometry(QtCore.QRect(153, 273, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ChampBlueTop.setFont(font)        
        self.ChampBlueTop.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                        "selection-background-color: rgb(255, 255, 255);\n"
                                        "text-color : black")
        self.ChampBlueTop.setObjectName("ChampBlueTop")        
        self.ChampBlueJungle = QtWidgets.QComboBox(self.centralwidget)
        self.ChampBlueJungle.setGeometry(QtCore.QRect(150, 390, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ChampBlueJungle.setFont(font)
        self.ChampBlueJungle.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ChampBlueJungle.setObjectName("ChampBlueJungle")
        self.ChampBlueMid = QtWidgets.QComboBox(self.centralwidget)
        self.ChampBlueMid.setGeometry(QtCore.QRect(150, 520, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ChampBlueMid.setFont(font)
        self.ChampBlueMid.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ChampBlueMid.setObjectName("ChampBlueMid")
        self.ChampBlueBot = QtWidgets.QComboBox(self.centralwidget)
        self.ChampBlueBot.setGeometry(QtCore.QRect(150, 640, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ChampBlueBot.setFont(font)
        self.ChampBlueBot.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ChampBlueBot.setObjectName("ChampBlueBot")
        self.ChampBlueSup = QtWidgets.QComboBox(self.centralwidget)
        self.ChampBlueSup.setGeometry(QtCore.QRect(150, 760, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ChampBlueSup.setFont(font)
        self.ChampBlueSup.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ChampBlueSup.setObjectName("ChampBlueSup")
        self.ChampRedTop = QtWidgets.QComboBox(self.centralwidget)
        self.ChampRedTop.setGeometry(QtCore.QRect(713, 274, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ChampRedTop.setFont(font)
        self.ChampRedTop.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ChampRedTop.setEditable(False)
        self.ChampRedTop.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.ChampRedTop.setObjectName("ChampRedTop")
        self.ChampRedJungle = QtWidgets.QComboBox(self.centralwidget)
        self.ChampRedJungle.setGeometry(QtCore.QRect(710, 400, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ChampRedJungle.setFont(font)
        self.ChampRedJungle.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ChampRedJungle.setObjectName("ChampRedJungle")
        self.ChampRedMid = QtWidgets.QComboBox(self.centralwidget)
        self.ChampRedMid.setGeometry(QtCore.QRect(710, 510, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ChampRedMid.setFont(font)
        self.ChampRedMid.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ChampRedMid.setObjectName("ChampRedMid")
        self.ChampRedBot = QtWidgets.QComboBox(self.centralwidget)
        self.ChampRedBot.setGeometry(QtCore.QRect(710, 640, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ChampRedBot.setFont(font)
        self.ChampRedBot.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ChampRedBot.setObjectName("ChampRedBot")
        self.ChampRedSup = QtWidgets.QComboBox(self.centralwidget)
        self.ChampRedSup.setGeometry(QtCore.QRect(710, 750, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ChampRedSup.setFont(font)
        self.ChampRedSup.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ChampRedSup.setObjectName("ChampRedSup")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1125, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionpgmLauncher = QtWidgets.QAction(MainWindow)
        self.actionpgmLauncher.setObjectName("actionpgmLauncher")

        self.retranslateUi(MainWindow)
        self.button_1.clicked.connect(self.actionpgmLauncher.trigger)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WEC - Data Alchemist Studio, 2021"))
        self.button_1.setText(_translate("MainWindow", "LANCER"))
        self.textBlueMain.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans Display Black\'; font-size:16pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.SNBlueTop.setText(_translate("MainWindow", "Toplaner name"))
        self.SNRedTop.setText(_translate("MainWindow", "Toplaner name"))
        self.SNRedJungle.setText(_translate("MainWindow", "Jungler name"))
        self.SNBlueJungle.setText(_translate("MainWindow", "Jungler name"))
        self.SNBlueMid.setText(_translate("MainWindow", "Midlaner name"))
        self.SNRedMid.setText(_translate("MainWindow", "Midlaner name"))
        self.SNBlueBot.setText(_translate("MainWindow", "Botlaner name"))
        self.SNRedBot.setText(_translate("MainWindow", "Botlaner name"))
        self.SNRedSup.setText(_translate("MainWindow", "Support name"))
        self.SNBlueSup.setText(_translate("MainWindow", "Support name"))
        self.actionpgmLauncher.setText(_translate("MainWindow", "pgmLauncher"))
        championList = fl.getChampionList()
        self.ChampBlueTop.addItems(championList)
        self.ChampBlueJungle.addItems(championList)
        self.ChampBlueMid.addItems(championList)
        self.ChampBlueBot.addItems(championList)
        self.ChampBlueSup.addItems(championList)
        self.ChampRedTop.addItems(championList)
        self.ChampRedJungle.addItems(championList)
        self.ChampRedMid.addItems(championList)
        self.ChampRedBot.addItems(championList)
        self.ChampRedSup.addItems(championList)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

